---
# Install smartmontools from source
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install build dependencies
- name: Install build dependencies
  package:
    name:
      "{{ smartmontools_build_dependencies }}"
    state: present

# Download, configure, build and install
- name: Download smartmontools from Git
  git:
    repo: "https://github.com/smartmontools/smartmontools.git"
    dest: "{{ smartmontools_src_location }}"
    version: 'RELEASE_7_1'

- name: Run autogen.sh
  command: ./autogen.sh
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "{{ smartmontools_src_location }}/smartmontools/configure"

- name: Run configure
  command: "./configure --with-nvme-devicescan"
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "{{ smartmontools_src_location }}/smartmontools/Makefile"
