---
# Install smartmontools from source
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Ensure there's no old version of smartmontools installed
- name: Remove any old (packaged) versions of smartmontools
  package:
    name: smartmontools
    state: absent

# Install build dependencies
- name: Install build dependencies
  package:
    name:
      "{{ smartmontools_build_dependencies }}"
    state: present

# If running on a CentOS 6 machine, install the SCL repo and devtoolset
- name: Install centos-release-scl-rh (special case for CentOS 6)
  package:
    name: centos-release-scl-rh
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6

- name: Install devtoolset-7 toolchain (special case for CentOS 6)
  package:
    name: devtoolset-7-toolchain
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6

# If running on a machine with systemd, install the development libraries
- name: Install systemd development libraries
  package:
    name:
      "{{ smartmontools_systemd_dev_libraries }}"
    state: present
  when: ansible_service_mgr == 'systemd' and smartmontools_install_systemd_stuff

# If running on a machine with SELinux, install the development libraries
- name: Install SELinux development libraries
  package:
    name:
      "{{ smartmontools_selinux_dev_libraries }}"
    state: present
  when: ansible_os_family == 'RedHat' and smartmontools_install_selinux_stuff

# Download, configure, build and install
- name: Download smartmontools from Git
  git:
    repo: "https://github.com/smartmontools/smartmontools.git"
    dest: "{{ smartmontools_src_location }}"
    version: 'RELEASE_7_1'

- name: Run autogen.sh
  command: ./autogen.sh
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "{{ smartmontools_src_location }}/smartmontools/configure"

- name: Run configure (without SELinux)
  command: "./configure --with-nvme-devicescan"
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "{{ smartmontools_src_location }}/smartmontools/Makefile"
  when: not ansible_os_family == 'RedHat'

- name: Run configure (with SELinux)
  command: "./configure --with-nvme-devicescan --with-selinux"
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "{{ smartmontools_src_location }}/smartmontools/Makefile"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7 and smartmontools_install_selinux_stuff

- name: Run configure via SCL (with SELinux, special case for CentOS 6)
  command: "scl enable devtoolset-7 -- ./configure --with-nvme-devicescan --with-selinux"
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "{{ smartmontools_src_location }}/smartmontools/Makefile"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6 and smartmontools_install_selinux_stuff

- name: Build and install smartmontools
  shell: "make && make install"
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "/usr/local/sbin/smartctl"
  when: not (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6)

- name: Build and install smartmontools via SCL (special case for CentOS 6)
  shell: "scl enable devtoolset-7 -- make && make install"
  args:
    chdir: "{{ smartmontools_src_location }}/smartmontools"
    creates: "/usr/local/sbin/smartctl"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6
