---
# Install smartmontools from source
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install build dependencies
- name: Install build dependencies
  package:
    name:
      "{{ smartmontools_build_dependencies }}"
    state: present

# Download, build and install
- name: Download smartmontools from Git
  git:
    repo: "https://github.com/smartmontools/smartmontools.git"
    dest: "{{ smartmontools_src_location }}"
    version: 'RELEASE_7_1'
