---
# Attempt to install from packages on RedHat OS family

# Installation
- name: Install smartmontools package (for EL7)
  yum:
    name: smartmontools
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
