---
# Attempt to install from packages on Debian OS family

# Preparation
- name: Enable backports repository (for Debian 10)
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports
    update_cache: true
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10' and smartmontools_install_from_backports

# Installation
- name: Install smartmontools package (for Ubuntu 20.04)
  apt:
    name: smartmontools
    state: present
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install smartmontools package from backports (for Ubuntu 18.04 and Debian 10)
  apt:
    name: smartmontools
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04' and smartmontools_install_from_backports
      or ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 10 and smartmontools_install_from_backports
