---
# Attempt to install from packages on Debian OS family

# Preparation
- name: Enable backports repository (for Debian 10)
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports
    update_cache: true
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10' and not smartmontools_install_from_source

# Installation
- name: Install smartmontools package from backports (for Ubuntu 18.04 and Debian 10)
  apt:
    name: smartmontools
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04' and not smartmontools_install_from_source
      or ansible_distribution == 'Debian' and ansible_distribution_major_version|int = 10 and not smartmontools_install_from_source

- name: Install smartmontools package (from Ubuntu 20.04 and Debian 11 onwards)
  apt:
    name: smartmontools
    state: present
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= '20' and not smartmontools_install_from_source
      or ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 11 and not smartmontools_install_from_source