---
- name: Converge
  hosts: all
  become: true

  vars:

  pre_tasks:
    - include_tasks: environment-prep.yml

  roles:
    - zorlin.smartmontools
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
