---
- name: Converge but install from source
  hosts: all
  become: true

  vars:
    smartmontools_install_from_source: true

  pre_tasks:
    - include_tasks: environment-prep.yml

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
    - zorlin.smartmontools
